namespace HizliSatis.Model
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class MikroEnt : DbContext
    {
        public MikroEnt()
            : base("name=MikroEnt")
        {
        }

        public virtual DbSet<ADAY_CARI_HESAPLAR> ADAY_CARI_HESAPLAR { get; set; }
        public virtual DbSet<ALINAN_TEKLIFLER> ALINAN_TEKLIFLER { get; set; }
        public virtual DbSet<ARIZA_GRUPLARI> ARIZA_GRUPLARI { get; set; }
        public virtual DbSet<ARIZA_SINIFLARI> ARIZA_SINIFLARI { get; set; }
        public virtual DbSet<ASORTI_TANIM_KODLARI> ASORTI_TANIM_KODLARI { get; set; }
        public virtual DbSet<ASORTI_TANIMLARI> ASORTI_TANIMLARI { get; set; }
        public virtual DbSet<ATIK_MUHASEBE_GRUPLARI> ATIK_MUHASEBE_GRUPLARI { get; set; }
        public virtual DbSet<AVM_CARI_HASILAT_HAREKETLERI> AVM_CARI_HASILAT_HAREKETLERI { get; set; }
        public virtual DbSet<AVM_CIRO_HAREKETLERI> AVM_CIRO_HAREKETLERI { get; set; }
        public virtual DbSet<AVM_SAYAC_HAREKETLERI> AVM_SAYAC_HAREKETLERI { get; set; }
        public virtual DbSet<AVM_SAYACLARI> AVM_SAYACLARI { get; set; }
        public virtual DbSet<AVMCIRO_TANIMLARI> AVMCIRO_TANIMLARI { get; set; }
        public virtual DbSet<AVMKAPI_HAREKETLERI> AVMKAPI_HAREKETLERI { get; set; }
        public virtual DbSet<AVMKAPI_TANIMLARI> AVMKAPI_TANIMLARI { get; set; }
        public virtual DbSet<AVMKIRA_ARTISLARI> AVMKIRA_ARTISLARI { get; set; }
        public virtual DbSet<AVMKIRA_ODEMELERI> AVMKIRA_ODEMELERI { get; set; }
        public virtual DbSet<AVMKIRA_TANIMLARI> AVMKIRA_TANIMLARI { get; set; }
        public virtual DbSet<BAGIMSIZ_BOLUM_TANIMLARI> BAGIMSIZ_BOLUM_TANIMLARI { get; set; }
        public virtual DbSet<BAKIM_HAREKETLERI> BAKIM_HAREKETLERI { get; set; }
        public virtual DbSet<BAKIM_KABUL_HAREKETLERI> BAKIM_KABUL_HAREKETLERI { get; set; }
        public virtual DbSet<BAKIM_PDI_TANIMLARI> BAKIM_PDI_TANIMLARI { get; set; }
        public virtual DbSet<BAKIM_SARFIYATLARI> BAKIM_SARFIYATLARI { get; set; }
        public virtual DbSet<BAKIM_SOZLESME_HAREKETLERI> BAKIM_SOZLESME_HAREKETLERI { get; set; }
        public virtual DbSet<BANKALAR> BANKALAR { get; set; }
        public virtual DbSet<BARKOD_ETIKET_TANIMLARI> BARKOD_ETIKET_TANIMLARI { get; set; }
        public virtual DbSet<BARKOD_TANIMLARI> BARKOD_TANIMLARI { get; set; }
        public virtual DbSet<BEDEN_HAREKETLERI> BEDEN_HAREKETLERI { get; set; }
        public virtual DbSet<BLOK_TANIMLARI> BLOK_TANIMLARI { get; set; }
        public virtual DbSet<BUTCE_DETAY> BUTCE_DETAY { get; set; }
        public virtual DbSet<BUTCE_MASTER> BUTCE_MASTER { get; set; }
        public virtual DbSet<BUTCELENEN_NAKIT_AKIS> BUTCELENEN_NAKIT_AKIS { get; set; }
        public virtual DbSet<CARI_DAGITIM_ANAHTARLARI> CARI_DAGITIM_ANAHTARLARI { get; set; }
        public virtual DbSet<CARI_DEGERLENDIRME_FORMU> CARI_DEGERLENDIRME_FORMU { get; set; }
        public virtual DbSet<CARI_EVRAKFORMLARI> CARI_EVRAKFORMLARI { get; set; }
        public virtual DbSet<CARI_HAREKET_BORC_ALACAK_ESLEME> CARI_HAREKET_BORC_ALACAK_ESLEME { get; set; }
        public virtual DbSet<CARI_HAREKET_ODEME_VADELERI> CARI_HAREKET_ODEME_VADELERI { get; set; }
        public virtual DbSet<CARI_HAREKETLER_SATIS_MALIYETLERI> CARI_HAREKETLER_SATIS_MALIYETLERI { get; set; }
        public virtual DbSet<CARI_HESAP_ADRESLERI> CARI_HESAP_ADRESLERI { get; set; }
        public virtual DbSet<CARI_HESAP_BOLGELERI> CARI_HESAP_BOLGELERI { get; set; }
        public virtual DbSet<CARI_HESAP_GRUPLARI> CARI_HESAP_GRUPLARI { get; set; }
        public virtual DbSet<CARI_HESAP_HAREKETLERI> CARI_HESAP_HAREKETLERI { get; set; }
        public virtual DbSet<CARI_HESAP_HAREKETLERI_EK> CARI_HESAP_HAREKETLERI_EK { get; set; }
        public virtual DbSet<CARI_HESAP_HAREKETLERI_OZET> CARI_HESAP_HAREKETLERI_OZET { get; set; }
        public virtual DbSet<CARI_HESAP_SOZLESMELERI> CARI_HESAP_SOZLESMELERI { get; set; }
        public virtual DbSet<CARI_HESAP_TASIT_PLAKALARI> CARI_HESAP_TASIT_PLAKALARI { get; set; }
        public virtual DbSet<CARI_HESAP_TEMINATLARI> CARI_HESAP_TEMINATLARI { get; set; }
        public virtual DbSet<CARI_HESAP_YETKILILERI> CARI_HESAP_YETKILILERI { get; set; }
        public virtual DbSet<CARI_HESAPLAR> CARI_HESAPLAR { get; set; }
        public virtual DbSet<CARI_MUSTAHSIL_TANIMLARI> CARI_MUSTAHSIL_TANIMLARI { get; set; }
        public virtual DbSet<CARI_PERFORMANS_KRITERLERI> CARI_PERFORMANS_KRITERLERI { get; set; }
        public virtual DbSet<CARI_PERSONEL_TANIMLARI> CARI_PERSONEL_TANIMLARI { get; set; }
        public virtual DbSet<CEKI_LISTESI> CEKI_LISTESI { get; set; }
        public virtual DbSet<CIHAZ_DURUMLARI> CIHAZ_DURUMLARI { get; set; }
        public virtual DbSet<CIHAZ_GRUPLARI> CIHAZ_GRUPLARI { get; set; }
        public virtual DbSet<CIHAZ_HAREKETLERI> CIHAZ_HAREKETLERI { get; set; }
        public virtual DbSet<CIHAZ_SORUNLARI> CIHAZ_SORUNLARI { get; set; }
        public virtual DbSet<CIRO_PRIM_KRITERLERI> CIRO_PRIM_KRITERLERI { get; set; }
        public virtual DbSet<CIRO_PRIMLERI> CIRO_PRIMLERI { get; set; }
        public virtual DbSet<COZGU_ATKI_TANIMLARI> COZGU_ATKI_TANIMLARI { get; set; }
        public virtual DbSet<DAGITIM_ANAHTARI_TANIMLARI> DAGITIM_ANAHTARI_TANIMLARI { get; set; }
        public virtual DbSet<DAGITIM_KONTROL> DAGITIM_KONTROL { get; set; }
        public virtual DbSet<DEMIRBAS_GRUPLARI> DEMIRBAS_GRUPLARI { get; set; }
        public virtual DbSet<DEMIRBAS_MALIYIL_TANIMLARI> DEMIRBAS_MALIYIL_TANIMLARI { get; set; }
        public virtual DbSet<DEMIRBASLAR> DEMIRBASLAR { get; set; }
        public virtual DbSet<DEPARTMANLAR> DEPARTMANLAR { get; set; }
        public virtual DbSet<DEPO_GRUPLARI> DEPO_GRUPLARI { get; set; }
        public virtual DbSet<DEPOLAR> DEPOLAR { get; set; }
        public virtual DbSet<DEPOLAR_ARASI_SIPARISLER> DEPOLAR_ARASI_SIPARISLER { get; set; }
        public virtual DbSet<DIIB_DETAYLARI> DIIB_DETAYLARI { get; set; }
        public virtual DbSet<DIIB_RECETELERI> DIIB_RECETELERI { get; set; }
        public virtual DbSet<DIIB_TANIMLARI> DIIB_TANIMLARI { get; set; }
        public virtual DbSet<DOKUMA_DESEN_TANIMLARI> DOKUMA_DESEN_TANIMLARI { get; set; }
        public virtual DbSet<DONEMLERE_YAYILAN_HIZMETLER> DONEMLERE_YAYILAN_HIZMETLER { get; set; }
        public virtual DbSet<E_DEFTER_HAREKETLERI> E_DEFTER_HAREKETLERI { get; set; }
        public virtual DbSet<E_FATURA_DETAYLARI> E_FATURA_DETAYLARI { get; set; }
        public virtual DbSet<E_FATURA_ISLEMLERI> E_FATURA_ISLEMLERI { get; set; }
        public virtual DbSet<E_FATURA_OPERASYON_LOGLARI> E_FATURA_OPERASYON_LOGLARI { get; set; }
        public virtual DbSet<E_FATURA_TANIMLARI> E_FATURA_TANIMLARI { get; set; }
        public virtual DbSet<E_FATURA_TEMEL_ITIRAZ> E_FATURA_TEMEL_ITIRAZ { get; set; }
        public virtual DbSet<EBELGE_EVRAK_HAREKETLERI> EBELGE_EVRAK_HAREKETLERI { get; set; }
        public virtual DbSet<EDI_TCGB_KALEMLERI> EDI_TCGB_KALEMLERI { get; set; }
        public virtual DbSet<EGITIM_ALT_GRUP_TANIMLARI> EGITIM_ALT_GRUP_TANIMLARI { get; set; }
        public virtual DbSet<EGITIM_DEVAM_KONTROL> EGITIM_DEVAM_KONTROL { get; set; }
        public virtual DbSet<EGITIM_GRUP_TANIMLARI> EGITIM_GRUP_TANIMLARI { get; set; }
        public virtual DbSet<EGITIM_GRUP_TIPLERI> EGITIM_GRUP_TIPLERI { get; set; }
        public virtual DbSet<EGITIM_KONU_TANIMLARI> EGITIM_KONU_TANIMLARI { get; set; }
        public virtual DbSet<EKIP_TANIMLARI> EKIP_TANIMLARI { get; set; }
        public virtual DbSet<ETIKET> ETIKET { get; set; }
        public virtual DbSet<ETIKETBAS> ETIKETBAS { get; set; }
        public virtual DbSet<EVRAK_ACIKLAMALARI> EVRAK_ACIKLAMALARI { get; set; }
        public virtual DbSet<EVRAK_BELGE_RESIMLERI> EVRAK_BELGE_RESIMLERI { get; set; }
        public virtual DbSet<EVRAK_GENEL_PARAMETRELERI> EVRAK_GENEL_PARAMETRELERI { get; set; }
        public virtual DbSet<FINANSAL_SOZLESME_TAKSITLERI> FINANSAL_SOZLESME_TAKSITLERI { get; set; }
        public virtual DbSet<FINANSAL_SOZLESMELER> FINANSAL_SOZLESMELER { get; set; }
        public virtual DbSet<FIRMA_KREDI_KARTI_TANIMLARI> FIRMA_KREDI_KARTI_TANIMLARI { get; set; }
        public virtual DbSet<FIRMA_MALIYIL_BEYANNAME_PARAMETRELERI> FIRMA_MALIYIL_BEYANNAME_PARAMETRELERI { get; set; }
        public virtual DbSet<FIRMA_MALIYIL_BILGILERI> FIRMA_MALIYIL_BILGILERI { get; set; }
        public virtual DbSet<FIRMA_MALIYIL_ISLETME_TANIMLARI> FIRMA_MALIYIL_ISLETME_TANIMLARI { get; set; }
        public virtual DbSet<FIRMA_MALIYIL_URETIM_PARAMETRELERI> FIRMA_MALIYIL_URETIM_PARAMETRELERI { get; set; }
        public virtual DbSet<FIRMA_NACE_TANIMLARI> FIRMA_NACE_TANIMLARI { get; set; }
        public virtual DbSet<FIRMA_SERBEST_HAREKET> FIRMA_SERBEST_HAREKET { get; set; }
        public virtual DbSet<FIRMA_TEMSILCILERI> FIRMA_TEMSILCILERI { get; set; }
        public virtual DbSet<FIRMALAR> FIRMALAR { get; set; }
        public virtual DbSet<GELIR_GIDER_TANIMLARI> GELIR_GIDER_TANIMLARI { get; set; }
        public virtual DbSet<GIDER_KATILIM_SOZLESMELERI> GIDER_KATILIM_SOZLESMELERI { get; set; }
        public virtual DbSet<HATALI1> HATALI1 { get; set; }
        public virtual DbSet<HATALI2> HATALI2 { get; set; }
        public virtual DbSet<HESAP_MERKEZ_ANAHTAR_TANIMLARI> HESAP_MERKEZ_ANAHTAR_TANIMLARI { get; set; }
        public virtual DbSet<HESAP_OZETI_ISLEM_KODLARI> HESAP_OZETI_ISLEM_KODLARI { get; set; }
        public virtual DbSet<HIZMET_ALIS_SOZLESMELERI> HIZMET_ALIS_SOZLESMELERI { get; set; }
        public virtual DbSet<HIZMET_HESAPLARI> HIZMET_HESAPLARI { get; set; }
        public virtual DbSet<HIZMET_MASRAF_GRUPLARI> HIZMET_MASRAF_GRUPLARI { get; set; }
        public virtual DbSet<HIZMET_MASRAF_SINIFLARI> HIZMET_MASRAF_SINIFLARI { get; set; }
        public virtual DbSet<HIZMET_MASRAF_TIPLERI> HIZMET_MASRAF_TIPLERI { get; set; }
        public virtual DbSet<HIZMET_SATIS_SOZLESMELERI> HIZMET_SATIS_SOZLESMELERI { get; set; }
        public virtual DbSet<IADE_TALEPLERI> IADE_TALEPLERI { get; set; }
        public virtual DbSet<IHRACAAT_KREDILERI> IHRACAAT_KREDILERI { get; set; }
        public virtual DbSet<IHRACAT_DOSYALARI> IHRACAT_DOSYALARI { get; set; }
        public virtual DbSet<IK_FORMU> IK_FORMU { get; set; }
        public virtual DbSet<IK_ISGORUSME> IK_ISGORUSME { get; set; }
        public virtual DbSet<IK_KRITER_GRUPLARI> IK_KRITER_GRUPLARI { get; set; }
        public virtual DbSet<IK_KRITER_TANIMLARI> IK_KRITER_TANIMLARI { get; set; }
        public virtual DbSet<ILISKILER> ILISKILER { get; set; }
        public virtual DbSet<IPTAL_NEDENLERI> IPTAL_NEDENLERI { get; set; }
        public virtual DbSet<IS_ILAN_DETAYLARI> IS_ILAN_DETAYLARI { get; set; }
        public virtual DbSet<IS_ILANLARI> IS_ILANLARI { get; set; }
        public virtual DbSet<IS_MERKEZLERI> IS_MERKEZLERI { get; set; }
        public virtual DbSet<ISEMIRLERI> ISEMIRLERI { get; set; }
        public virtual DbSet<ISEMRI_MALZEME_DURUMLARI> ISEMRI_MALZEME_DURUMLARI { get; set; }
        public virtual DbSet<ISEMRI_MUHASEBE_GRUPLARI> ISEMRI_MUHASEBE_GRUPLARI { get; set; }
        public virtual DbSet<ISEMRI_STOK_TUKETIMLERI> ISEMRI_STOK_TUKETIMLERI { get; set; }
        public virtual DbSet<ISLETME_HAREKET_DETAYI> ISLETME_HAREKET_DETAYI { get; set; }
        public virtual DbSet<ISLETME_HAREKETLERI> ISLETME_HAREKETLERI { get; set; }
        public virtual DbSet<ISLETME_HESAP_PLANI> ISLETME_HESAP_PLANI { get; set; }
        public virtual DbSet<ISMERKEZI_GRUPLARI> ISMERKEZI_GRUPLARI { get; set; }
        public virtual DbSet<ISTASYON_ADALARI> ISTASYON_ADALARI { get; set; }
        public virtual DbSet<ISTASYON_SAYAC_HAREKET_DETAYLARI> ISTASYON_SAYAC_HAREKET_DETAYLARI { get; set; }
        public virtual DbSet<ISTASYON_SAYAC_HAREKETLERI> ISTASYON_SAYAC_HAREKETLERI { get; set; }
        public virtual DbSet<ISTASYON_SAYACLARI> ISTASYON_SAYACLARI { get; set; }
        public virtual DbSet<ISTASYON_VARDIYA_CALISANLARI> ISTASYON_VARDIYA_CALISANLARI { get; set; }
        public virtual DbSet<ISTASYON_VARDIYA_SATISLARI> ISTASYON_VARDIYA_SATISLARI { get; set; }
        public virtual DbSet<ISTASYON_VARDIYA_TAHSILATLARI> ISTASYON_VARDIYA_TAHSILATLARI { get; set; }
        public virtual DbSet<ITHALAT_DOSYALARI> ITHALAT_DOSYALARI { get; set; }
        public virtual DbSet<ITHALAT_MUHASEBE_GRUPLARI> ITHALAT_MUHASEBE_GRUPLARI { get; set; }
        public virtual DbSet<KALIP_APARAT_TANIMLARI> KALIP_APARAT_TANIMLARI { get; set; }
        public virtual DbSet<KAPAMA_NEDENLERI_TANIMLARI> KAPAMA_NEDENLERI_TANIMLARI { get; set; }
        public virtual DbSet<KARGO_GONDERILERI> KARGO_GONDERILERI { get; set; }
        public virtual DbSet<KARGO_TANIMLARI> KARGO_TANIMLARI { get; set; }
        public virtual DbSet<KASALAR> KASALAR { get; set; }
        public virtual DbSet<KAT_TANIMLARI> KAT_TANIMLARI { get; set; }
        public virtual DbSet<KIRA_TANIMLARI> KIRA_TANIMLARI { get; set; }
        public virtual DbSet<KIRALAMA_HAREKETLERI> KIRALAMA_HAREKETLERI { get; set; }
        public virtual DbSet<KIRALAMA_MMO_TANIMLARI> KIRALAMA_MMO_TANIMLARI { get; set; }
        public virtual DbSet<KIRALAMA_SEVK_HAREKETLERI> KIRALAMA_SEVK_HAREKETLERI { get; set; }
        public virtual DbSet<KIRALAMA_SOZLESMELERI> KIRALAMA_SOZLESMELERI { get; set; }
        public virtual DbSet<KIRALAMA_TALEP_HAREKETLERI> KIRALAMA_TALEP_HAREKETLERI { get; set; }
        public virtual DbSet<KIRALAMA_TEKLIF_HAREKETLERI> KIRALAMA_TEKLIF_HAREKETLERI { get; set; }
        public virtual DbSet<KIRALAMA_TEKLIF_REVIZYONLARI> KIRALAMA_TEKLIF_REVIZYONLARI { get; set; }
        public virtual DbSet<KISA_MESAJ_SABLONLARI> KISA_MESAJ_SABLONLARI { get; set; }
        public virtual DbSet<KONSINYE_HAREKETLERI> KONSINYE_HAREKETLERI { get; set; }
        public virtual DbSet<KONSINYE_HAREKETLERI_OZET> KONSINYE_HAREKETLERI_OZET { get; set; }
        public virtual DbSet<KREDI_KARTLARI> KREDI_KARTLARI { get; set; }
        public virtual DbSet<KREDI_SOZLESMESI_TAKSIT_TANIMLARI> KREDI_SOZLESMESI_TAKSIT_TANIMLARI { get; set; }
        public virtual DbSet<KREDI_SOZLESMESI_TANIMLARI> KREDI_SOZLESMESI_TANIMLARI { get; set; }
        public virtual DbSet<KULLANICI_ONAY_TANIMLARI> KULLANICI_ONAY_TANIMLARI { get; set; }
        public virtual DbSet<MAKINA_BAKIM_ISEMIRLERI> MAKINA_BAKIM_ISEMIRLERI { get; set; }
        public virtual DbSet<MAKINA_GRUPLARI> MAKINA_GRUPLARI { get; set; }
        public virtual DbSet<MAKINA_HAREKETLERI> MAKINA_HAREKETLERI { get; set; }
        public virtual DbSet<MAKINA_SORUNLARI> MAKINA_SORUNLARI { get; set; }
        public virtual DbSet<MAKINALAR> MAKINALAR { get; set; }
        public virtual DbSet<MALI_TABLOLAR> MALI_TABLOLAR { get; set; }
        public virtual DbSet<MASRAF_HESAPLARI> MASRAF_HESAPLARI { get; set; }
        public virtual DbSet<MERKEZ> MERKEZ { get; set; }
        public virtual DbSet<MUHASEBE_FIS_DETAYLARI> MUHASEBE_FIS_DETAYLARI { get; set; }
        public virtual DbSet<MUHASEBE_FIS_GRUBU_TANIMLARI> MUHASEBE_FIS_GRUBU_TANIMLARI { get; set; }
        public virtual DbSet<MUHASEBE_FISLERI> MUHASEBE_FISLERI { get; set; }
        public virtual DbSet<MUHASEBE_FISLERI_OZET> MUHASEBE_FISLERI_OZET { get; set; }
        public virtual DbSet<MUHASEBE_HESAP_BUTCESI> MUHASEBE_HESAP_BUTCESI { get; set; }
        public virtual DbSet<MUHASEBE_HESAP_GRUPLARI> MUHASEBE_HESAP_GRUPLARI { get; set; }
        public virtual DbSet<MUHASEBE_HESAP_PLANI> MUHASEBE_HESAP_PLANI { get; set; }
        public virtual DbSet<MUHTASAR_GRUPLARI> MUHTASAR_GRUPLARI { get; set; }
        public virtual DbSet<MULTIKOD_TANIMLARI> MULTIKOD_TANIMLARI { get; set; }
        public virtual DbSet<mye_AttachedFiles> mye_AttachedFiles { get; set; }
        public virtual DbSet<mye_CubeItems> mye_CubeItems { get; set; }
        public virtual DbSet<mye_Cubes> mye_Cubes { get; set; }
        public virtual DbSet<mye_Favorites> mye_Favorites { get; set; }
        public virtual DbSet<mye_ImageData> mye_ImageData { get; set; }
        public virtual DbSet<mye_OnlineData> mye_OnlineData { get; set; }
        public virtual DbSet<mye_OnlineImageData> mye_OnlineImageData { get; set; }
        public virtual DbSet<mye_OnlineTextData> mye_OnlineTextData { get; set; }
        public virtual DbSet<mye_OnlineUserData> mye_OnlineUserData { get; set; }
        public virtual DbSet<mye_OnlineUserDataScheme> mye_OnlineUserDataScheme { get; set; }
        public virtual DbSet<mye_PlanImages> mye_PlanImages { get; set; }
        public virtual DbSet<mye_PlanPins> mye_PlanPins { get; set; }
        public virtual DbSet<mye_TableFilters> mye_TableFilters { get; set; }
        public virtual DbSet<mye_TextData> mye_TextData { get; set; }
        public virtual DbSet<mye_UserDataScheme> mye_UserDataScheme { get; set; }
        public virtual DbSet<NAKAKSRV> NAKAKSRV { get; set; }
        public virtual DbSet<NAKIT_AKIS_TABLOSU> NAKIT_AKIS_TABLOSU { get; set; }
        public virtual DbSet<ODEME_EMIRLERI> ODEME_EMIRLERI { get; set; }
        public virtual DbSet<ODEME_EMRI_ACILISLARI> ODEME_EMRI_ACILISLARI { get; set; }
        public virtual DbSet<ODEME_LISTESI> ODEME_LISTESI { get; set; }
        public virtual DbSet<ODEME_PLANLARI> ODEME_PLANLARI { get; set; }
        public virtual DbSet<OKC_HAREKETLERI> OKC_HAREKETLERI { get; set; }
        public virtual DbSet<ONAYLI_EVRAKLAR> ONAYLI_EVRAKLAR { get; set; }
        public virtual DbSet<ONL_RED> ONL_RED { get; set; }
        public virtual DbSet<OPERASYON_MALIYET_DETAYLARI> OPERASYON_MALIYET_DETAYLARI { get; set; }
        public virtual DbSet<OPERASYON_RECETELERI> OPERASYON_RECETELERI { get; set; }
        public virtual DbSet<OZEL_MAHSUP_DETAY_TANIMLARI> OZEL_MAHSUP_DETAY_TANIMLARI { get; set; }
        public virtual DbSet<PARTILOT> PARTILOT { get; set; }
        public virtual DbSet<PERIYODIK_EVRAKLAR> PERIYODIK_EVRAKLAR { get; set; }
        public virtual DbSet<PERSONEL_AILE_TANIMLARI> PERSONEL_AILE_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_ALINAN_EGITIMLER> PERSONEL_ALINAN_EGITIMLER { get; set; }
        public virtual DbSet<PERSONEL_AVANS_TALEPLERI> PERSONEL_AVANS_TALEPLERI { get; set; }
        public virtual DbSet<PERSONEL_BASVURU_PUAN_DEGERLENDIRMELERI> PERSONEL_BASVURU_PUAN_DEGERLENDIRMELERI { get; set; }
        public virtual DbSet<PERSONEL_BASVURU_PUAN_TANIMLARI> PERSONEL_BASVURU_PUAN_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_BELGE_DETAYLARI> PERSONEL_BELGE_DETAYLARI { get; set; }
        public virtual DbSet<PERSONEL_BELGE_GRUPLARI> PERSONEL_BELGE_GRUPLARI { get; set; }
        public virtual DbSet<PERSONEL_BELGE_TANIMLARI> PERSONEL_BELGE_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_BOLGELERI> PERSONEL_BOLGELERI { get; set; }
        public virtual DbSet<PERSONEL_BOLUM_TANIMLARI> PERSONEL_BOLUM_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_CALISMA_TANIMLARI> PERSONEL_CALISMA_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_DEVAM_KONTROL> PERSONEL_DEVAM_KONTROL { get; set; }
        public virtual DbSet<PERSONEL_DEVAM_KONTROL_NEDENLERI> PERSONEL_DEVAM_KONTROL_NEDENLERI { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_DETAYLARI> PERSONEL_EGITIM_DETAYLARI { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_SINAVLARI> PERSONEL_EGITIM_SINAVLARI { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_TALEPLERI> PERSONEL_EGITIM_TALEPLERI { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_TANIMLARI> PERSONEL_EGITIM_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_EGITIM_YERI_TANIMLARI> PERSONEL_EGITIM_YERI_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_EGITMENLERI> PERSONEL_EGITMENLERI { get; set; }
        public virtual DbSet<PERSONEL_EKKAZANC_TANIMLARI> PERSONEL_EKKAZANC_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_GIRILEN_SINAVLAR> PERSONEL_GIRILEN_SINAVLAR { get; set; }
        public virtual DbSet<PERSONEL_GOREV_TANIMLARI> PERSONEL_GOREV_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_ICRA_ODEMELERI> PERSONEL_ICRA_ODEMELERI { get; set; }
        public virtual DbSet<PERSONEL_ICRA_TANIMLARI> PERSONEL_ICRA_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_IS_BASVURULARI> PERSONEL_IS_BASVURULARI { get; set; }
        public virtual DbSet<PERSONEL_IS_GRUP_TANIMLARI> PERSONEL_IS_GRUP_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_IZIN_TALEPLERI> PERSONEL_IZIN_TALEPLERI { get; set; }
        public virtual DbSet<PERSONEL_IZINLERI> PERSONEL_IZINLERI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_CALISANLARI> PERSONEL_KADRO_CALISANLARI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_EGITIMLERI> PERSONEL_KADRO_EGITIMLERI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_LIMITLERI> PERSONEL_KADRO_LIMITLERI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_NITELIKLERI> PERSONEL_KADRO_NITELIKLERI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_PERFORMANSLARI> PERSONEL_KADRO_PERFORMANSLARI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_SORUMLULUKLARI> PERSONEL_KADRO_SORUMLULUKLARI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_TANIMLARI> PERSONEL_KADRO_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_TARIHCESI> PERSONEL_KADRO_TARIHCESI { get; set; }
        public virtual DbSet<PERSONEL_KADRO_YETKILERI> PERSONEL_KADRO_YETKILERI { get; set; }
        public virtual DbSet<PERSONEL_MUHASEBE_GRUPLARI> PERSONEL_MUHASEBE_GRUPLARI { get; set; }
        public virtual DbSet<PERSONEL_NITELIK_TANIMLARI> PERSONEL_NITELIK_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_NITELIKLERI> PERSONEL_NITELIKLERI { get; set; }
        public virtual DbSet<PERSONEL_PERFORMANS_TANIMLARI> PERSONEL_PERFORMANS_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_PERFORMANSLAR> PERSONEL_PERFORMANSLAR { get; set; }
        public virtual DbSet<PERSONEL_PRIM_DAGITIM_TANIMLARI> PERSONEL_PRIM_DAGITIM_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_SINAV_GRUPLARI> PERSONEL_SINAV_GRUPLARI { get; set; }
        public virtual DbSet<PERSONEL_SINAV_LISTESI> PERSONEL_SINAV_LISTESI { get; set; }
        public virtual DbSet<PERSONEL_SINAV_SORU_TANIMLARI> PERSONEL_SINAV_SORU_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_SINAV_SORULARI> PERSONEL_SINAV_SORULARI { get; set; }
        public virtual DbSet<PERSONEL_SINAV_TANIMLARI> PERSONEL_SINAV_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_SORUMLULUK_TANIMLARI> PERSONEL_SORUMLULUK_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_SOSYALYARDIM_TANIMLARI> PERSONEL_SOSYALYARDIM_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_SSK_TANIMLARI> PERSONEL_SSK_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_TAHAKKUK_OZETLERI> PERSONEL_TAHAKKUK_OZETLERI { get; set; }
        public virtual DbSet<PERSONEL_TAHAKKUK_OZETLERI_SIMULATOR> PERSONEL_TAHAKKUK_OZETLERI_SIMULATOR { get; set; }
        public virtual DbSet<PERSONEL_TAHAKKUKLARI> PERSONEL_TAHAKKUKLARI { get; set; }
        public virtual DbSet<PERSONEL_TAHAKKUKLARI_SIMULATOR> PERSONEL_TAHAKKUKLARI_SIMULATOR { get; set; }
        public virtual DbSet<PERSONEL_TALEPLERI> PERSONEL_TALEPLERI { get; set; }
        public virtual DbSet<PERSONEL_UNVAN_TANIMLARI> PERSONEL_UNVAN_TANIMLARI { get; set; }
        public virtual DbSet<PERSONEL_YETKI_TANIMLARI> PERSONEL_YETKI_TANIMLARI { get; set; }
        public virtual DbSet<PERSONELLER> PERSONELLER { get; set; }
        public virtual DbSet<POS_ODEME_TANIMLARI> POS_ODEME_TANIMLARI { get; set; }
        public virtual DbSet<POS_SOZLESME_TANIMLARI> POS_SOZLESME_TANIMLARI { get; set; }
        public virtual DbSet<POSHATA> POSHATA { get; set; }
        public virtual DbSet<POZISYON_BAYRAKLARI> POZISYON_BAYRAKLARI { get; set; }
        public virtual DbSet<PROFORMA_FIYAT_DEGISIKLIKLERI> PROFORMA_FIYAT_DEGISIKLIKLERI { get; set; }
        public virtual DbSet<PROFORMA_SATINALMA_SARTLARI> PROFORMA_SATINALMA_SARTLARI { get; set; }
        public virtual DbSet<PROFORMA_SIPARISLER> PROFORMA_SIPARISLER { get; set; }
        public virtual DbSet<PROGRAM_LOGLARI> PROGRAM_LOGLARI { get; set; }
        public virtual DbSet<PROJELER> PROJELER { get; set; }
        public virtual DbSet<PROMOPUAN_TANIMLARI> PROMOPUAN_TANIMLARI { get; set; }
        public virtual DbSet<PROMOSYON_HAREKETLERI> PROMOSYON_HAREKETLERI { get; set; }
        public virtual DbSet<PROMOSYON_TANIMLARI> PROMOSYON_TANIMLARI { get; set; }
        public virtual DbSet<PUAN_HEDIYE_CEKI_HAREKETLERI> PUAN_HEDIYE_CEKI_HAREKETLERI { get; set; }
        public virtual DbSet<RAF_ADRESLERI> RAF_ADRESLERI { get; set; }
        public virtual DbSet<RAKIP_STOK_DEPO_DETAYLARI> RAKIP_STOK_DEPO_DETAYLARI { get; set; }
        public virtual DbSet<RAKIP_STOKLAR> RAKIP_STOKLAR { get; set; }
        public virtual DbSet<rb_folder> rb_folder { get; set; }
        public virtual DbSet<rb_item> rb_item { get; set; }
        public virtual DbSet<RECETE_KRITERLERI> RECETE_KRITERLERI { get; set; }
        public virtual DbSet<SATINALMA_SARTLARI> SATINALMA_SARTLARI { get; set; }
        public virtual DbSet<SATINALMA_TALEPLERI> SATINALMA_TALEPLERI { get; set; }
        public virtual DbSet<SATIS_SARTLARI> SATIS_SARTLARI { get; set; }
        public virtual DbSet<SAYIM_SONUCLARI> SAYIM_SONUCLARI { get; set; }
        public virtual DbSet<SELF> SELF { get; set; }
        public virtual DbSet<SERVIS_HAREKETLERI> SERVIS_HAREKETLERI { get; set; }
        public virtual DbSet<SERVIS_ISEMIRLERI> SERVIS_ISEMIRLERI { get; set; }
        public virtual DbSet<SERVIS_MALZEME_PLANLARI> SERVIS_MALZEME_PLANLARI { get; set; }
        public virtual DbSet<SERVIS_ROTA_PLANLARI> SERVIS_ROTA_PLANLARI { get; set; }
        public virtual DbSet<SHOP_PROMOSYON_KONTROL> SHOP_PROMOSYON_KONTROL { get; set; }
        public virtual DbSet<SHOP_PROMOSYON_SORGULARI> SHOP_PROMOSYON_SORGULARI { get; set; }
        public virtual DbSet<SHOP_PROMOSYON_TANIMLARI> SHOP_PROMOSYON_TANIMLARI { get; set; }
        public virtual DbSet<SHOP_PROMOSYON_UYGULAMA_TANIMLARI> SHOP_PROMOSYON_UYGULAMA_TANIMLARI { get; set; }
        public virtual DbSet<SIKAYET_TANIMLARI> SIKAYET_TANIMLARI { get; set; }
        public virtual DbSet<SIPARIS_ESLEME> SIPARIS_ESLEME { get; set; }
        public virtual DbSet<SIPARISLER> SIPARISLER { get; set; }
        public virtual DbSet<SIPARISLER_OZET> SIPARISLER_OZET { get; set; }
        public virtual DbSet<SITE_TANIMLARI> SITE_TANIMLARI { get; set; }
        public virtual DbSet<SON_KULLANICILAR> SON_KULLANICILAR { get; set; }
        public virtual DbSet<SORUMLULUK_MERKEZLERI> SORUMLULUK_MERKEZLERI { get; set; }
        public virtual DbSet<STOK_ALT_GRUPLARI> STOK_ALT_GRUPLARI { get; set; }
        public virtual DbSet<STOK_ALTERNATIFLERI> STOK_ALTERNATIFLERI { get; set; }
        public virtual DbSet<STOK_AMBALAJLARI> STOK_AMBALAJLARI { get; set; }
        public virtual DbSet<STOK_ANA_GRUPLARI> STOK_ANA_GRUPLARI { get; set; }
        public virtual DbSet<STOK_ANAHAMMADDELERI> STOK_ANAHAMMADDELERI { get; set; }
        public virtual DbSet<STOK_BAG_TANIMLARI> STOK_BAG_TANIMLARI { get; set; }
        public virtual DbSet<STOK_BEDEN_TANIMLARI> STOK_BEDEN_TANIMLARI { get; set; }
        public virtual DbSet<STOK_CARI_ISKONTO_TANIMLARI> STOK_CARI_ISKONTO_TANIMLARI { get; set; }
        public virtual DbSet<STOK_CARI_KAMPANYA_TANIMLARI> STOK_CARI_KAMPANYA_TANIMLARI { get; set; }
        public virtual DbSet<STOK_DEPO_DETAYLARI> STOK_DEPO_DETAYLARI { get; set; }
        public virtual DbSet<STOK_FIYAT_DEGISIKLIKLERI> STOK_FIYAT_DEGISIKLIKLERI { get; set; }
        public virtual DbSet<STOK_HAREKET_MALIYET_DETAYLARI> STOK_HAREKET_MALIYET_DETAYLARI { get; set; }
        public virtual DbSet<STOK_HAREKETLERI> STOK_HAREKETLERI { get; set; }
        public virtual DbSet<STOK_HAREKETLERI_EK> STOK_HAREKETLERI_EK { get; set; }
        public virtual DbSet<STOK_HAREKETLERI_OZET> STOK_HAREKETLERI_OZET { get; set; }
        public virtual DbSet<STOK_HAREKETLERINE_MALIYET_YANSITMA> STOK_HAREKETLERINE_MALIYET_YANSITMA { get; set; }
        public virtual DbSet<STOK_KALITE_KONTROL_TANIMLARI> STOK_KALITE_KONTROL_TANIMLARI { get; set; }
        public virtual DbSet<STOK_KALKON> STOK_KALKON { get; set; }
        public virtual DbSet<STOK_KATEGORILERI> STOK_KATEGORILERI { get; set; }
        public virtual DbSet<STOK_KOD_ALTERNATIFLERI> STOK_KOD_ALTERNATIFLERI { get; set; }
        public virtual DbSet<STOK_MARKALARI> STOK_MARKALARI { get; set; }
        public virtual DbSet<STOK_MODEL_TANIMLARI> STOK_MODEL_TANIMLARI { get; set; }
        public virtual DbSet<STOK_MUHASEBE_GRUPLARI> STOK_MUHASEBE_GRUPLARI { get; set; }
        public virtual DbSet<STOK_PAKET_TANIMLARI> STOK_PAKET_TANIMLARI { get; set; }
        public virtual DbSet<STOK_PRIM_TANIMLARI> STOK_PRIM_TANIMLARI { get; set; }
        public virtual DbSet<STOK_RENK_TANIMLARI> STOK_RENK_TANIMLARI { get; set; }
        public virtual DbSet<STOK_REYONLARI> STOK_REYONLARI { get; set; }
        public virtual DbSet<STOK_REZERVASYONLARI> STOK_REZERVASYONLARI { get; set; }
        public virtual DbSet<STOK_SARF_RECETELERI> STOK_SARF_RECETELERI { get; set; }
        public virtual DbSet<STOK_SATIS_FIYAT_LISTE_TANIMLARI> STOK_SATIS_FIYAT_LISTE_TANIMLARI { get; set; }
        public virtual DbSet<STOK_SATIS_FIYAT_LISTELERI> STOK_SATIS_FIYAT_LISTELERI { get; set; }
        public virtual DbSet<STOK_SEKTORLERI> STOK_SEKTORLERI { get; set; }
        public virtual DbSet<STOK_SERINO_TANIMLARI> STOK_SERINO_TANIMLARI { get; set; }
        public virtual DbSet<STOK_URETICILERI> STOK_URETICILERI { get; set; }
        public virtual DbSet<STOK_YILSEZON_TANIMLARI> STOK_YILSEZON_TANIMLARI { get; set; }
        public virtual DbSet<STOKLAR> STOKLAR { get; set; }
        public virtual DbSet<SUBE> SUBE { get; set; }
        public virtual DbSet<SUBELER> SUBELER { get; set; }
        public virtual DbSet<TAKVIM_VARDIYA_DETAYLARI> TAKVIM_VARDIYA_DETAYLARI { get; set; }
        public virtual DbSet<TAKVIMLER> TAKVIMLER { get; set; }
        public virtual DbSet<TAMAMLAYICI_STOKLAR> TAMAMLAYICI_STOKLAR { get; set; }
        public virtual DbSet<TEKLIF_TANIMLARI> TEKLIF_TANIMLARI { get; set; }
        public virtual DbSet<TEMEL_ROTALAR> TEMEL_ROTALAR { get; set; }
        public virtual DbSet<TEMEL_URUN_RECETELERI> TEMEL_URUN_RECETELERI { get; set; }
        public virtual DbSet<TESLIM_TURLERI> TESLIM_TURLERI { get; set; }
        public virtual DbSet<TRANSFER_IRSALIYELERI> TRANSFER_IRSALIYELERI { get; set; }
        public virtual DbSet<TRANSFER_SIPARISLERI> TRANSFER_SIPARISLERI { get; set; }
        public virtual DbSet<UFRS_CARI_HAREKET_DEGERLERI> UFRS_CARI_HAREKET_DEGERLERI { get; set; }
        public virtual DbSet<UFRS_FISLERI> UFRS_FISLERI { get; set; }
        public virtual DbSet<UFRS_SOZLESMELERI> UFRS_SOZLESMELERI { get; set; }
        public virtual DbSet<UFRS_STOK_DEGER_DUSUKLUGU> UFRS_STOK_DEGER_DUSUKLUGU { get; set; }
        public virtual DbSet<UFRS_STOK_HAREKET_DEGERLERI> UFRS_STOK_HAREKET_DEGERLERI { get; set; }
        public virtual DbSet<URETIM_GECIKME_NEDENLERI> URETIM_GECIKME_NEDENLERI { get; set; }
        public virtual DbSet<URETIM_HATALARI> URETIM_HATALARI { get; set; }
        public virtual DbSet<URETIM_KOMBINE_HAMMADDE_HAREKETLERI> URETIM_KOMBINE_HAMMADDE_HAREKETLERI { get; set; }
        public virtual DbSet<URETIM_KOMBINE_URUN_HAREKETLERI> URETIM_KOMBINE_URUN_HAREKETLERI { get; set; }
        public virtual DbSet<URETIM_MALIYET_DEVIR> URETIM_MALIYET_DEVIR { get; set; }
        public virtual DbSet<URETIM_MALZEME_PLANLAMA> URETIM_MALZEME_PLANLAMA { get; set; }
        public virtual DbSet<URETIM_OPERASYON_CALISANLARI> URETIM_OPERASYON_CALISANLARI { get; set; }
        public virtual DbSet<URETIM_OPERASYON_DETAYLARI> URETIM_OPERASYON_DETAYLARI { get; set; }
        public virtual DbSet<URETIM_OPERASYON_GECIKMELERI> URETIM_OPERASYON_GECIKMELERI { get; set; }
        public virtual DbSet<URETIM_OPERASYON_HAREKETLERI> URETIM_OPERASYON_HAREKETLERI { get; set; }
        public virtual DbSet<URETIM_OPERASYON_HATALARI> URETIM_OPERASYON_HATALARI { get; set; }
        public virtual DbSet<URETIM_OPERASYONLARI> URETIM_OPERASYONLARI { get; set; }
        public virtual DbSet<URETIM_PLAN_MATRISI> URETIM_PLAN_MATRISI { get; set; }
        public virtual DbSet<URETIM_PLAN_MATRISI_DETAY> URETIM_PLAN_MATRISI_DETAY { get; set; }
        public virtual DbSet<URETIM_ROTA_PLANLARI> URETIM_ROTA_PLANLARI { get; set; }
        public virtual DbSet<URETIM_TALEPLERI> URETIM_TALEPLERI { get; set; }
        public virtual DbSet<URUN_RECETE_REVIZYONLARI> URUN_RECETE_REVIZYONLARI { get; set; }
        public virtual DbSet<URUN_RECETELERI> URUN_RECETELERI { get; set; }
        public virtual DbSet<URUN_ROTA_DETAYLARI> URUN_ROTA_DETAYLARI { get; set; }
        public virtual DbSet<URUN_ROTALARI> URUN_ROTALARI { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
        public virtual DbSet<VARDIYALAR> VARDIYALAR { get; set; }
        public virtual DbSet<VERGI_FON_TANIMLARI> VERGI_FON_TANIMLARI { get; set; }
        public virtual DbSet<VERGI_MUHASEBE_KODLARI> VERGI_MUHASEBE_KODLARI { get; set; }
        public virtual DbSet<VERGI_TAHAKKUKLARI> VERGI_TAHAKKUKLARI { get; set; }
        public virtual DbSet<VERI_TABANI_PARAMETRELERI> VERI_TABANI_PARAMETRELERI { get; set; }
        public virtual DbSet<VERILEN_TEKLIFLER> VERILEN_TEKLIFLER { get; set; }
        public virtual DbSet<YASAKLI_KAYITLAR> YASAKLI_KAYITLAR { get; set; }
        public virtual DbSet<YASAL_PARAMETRELER> YASAL_PARAMETRELER { get; set; }
        public virtual DbSet<YATIRIM_TESVIK_DETAYLARI> YATIRIM_TESVIK_DETAYLARI { get; set; }
        public virtual DbSet<YATIRIM_TESVIKLERI> YATIRIM_TESVIKLERI { get; set; }
        public virtual DbSet<YOLCU_TANIMLARI> YOLCU_TANIMLARI { get; set; }
        public virtual DbSet<YUKLEME_KABUL> YUKLEME_KABUL { get; set; }
        public virtual DbSet<YUKLEME_KABUL_DETAY> YUKLEME_KABUL_DETAY { get; set; }
        public virtual DbSet<ZIMMET_YERLERI> ZIMMET_YERLERI { get; set; }
        public virtual DbSet<ZIYARET_HAREKETLERI> ZIYARET_HAREKETLERI { get; set; }
        public virtual DbSet<TEMP_WORKDATAFILE_O> TEMP_WORKDATAFILE_O { get; set; }
        public virtual DbSet<TEMP_WORKDATAFILE_S> TEMP_WORKDATAFILE_S { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ISEMIRLERI>()
                .Property(e => e.is_SipSafha)
                .IsFixedLength();

            modelBuilder.Entity<PERSONEL_SOSYALYARDIM_TANIMLARI>()
                .Property(e => e.PSY_GunAy)
                .IsFixedLength();

            modelBuilder.Entity<URUNLER>()
                .Property(e => e.uru_isemriID)
                .IsFixedLength();

            modelBuilder.Entity<VERI_TABANI_PARAMETRELERI>()
                .Property(e => e.Param_buf)
                .IsFixedLength();
        }
    }
}
