using HizliSatis.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace HizliSatis
{
    public partial class AyarlarForm : DevExpress.XtraEditors.XtraForm
    {
        public AyarlarForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
        }
        SatisEnt db = new SatisEnt();
        private void BtnKaydet_Click(object sender, EventArgs e)
        {
            var sorgu = db.Ayarlar.Select(u => u).Count();
            if (sorgu == 0)
            {
                Ayarlar ayr = new Ayarlar();
                ayr.Nakit_Seri_No = txtNakitSeri.Text;
                ayr.Depo_Kodu = txtDepoKodu.EditValue.ToString();
                ayr.Cari_Kodu = txtCariKodu.EditValue.ToString();
                ayr.Kurulum_Tarihi = Convert.ToDateTime(txtTarih.Text);
                ayr.Plasiyer_Kodu = txtPlasiyerKodu.EditValue.ToString();
                ayr.Kasa_Seri = txtKasaSeri.Text;
                ayr.Nakit_Kasa_Kodu = txtNakitKasa.EditValue.ToString();
                ayr.KKart_Kasa_Kodu = txtKartKasakodu.EditValue.ToString();
                ayr.KKart_Kasa_Aciklama = txtKKartKasaAciklama.Text;
                ayr.Odeme_Sekil1_Kodu = txtOdeme1Kodu.EditValue.ToString();
                ayr.Odeme_Sekil1_Aciklama = txtOdeme1Aciklama.Text;
                ayr.Odeme_Sekil2_Kodu = txtOdeme2Kodu.EditValue.ToString();
                ayr.Odeme_Sekil2_Aciklama = txtOdeme2Aciklama.Text;
                ayr.Odeme_Sekil3_Kodu = txtOdeme3Kodu.EditValue.ToString();
                ayr.Odeme_Sekil3_Aciklama = txtOdeme3Aciklama.Text;
                ayr.Odeme_Sekil4_Kodu = txtOdeme4Kodu.EditValue.ToString();
                ayr.Odeme_Sekil4_Aciklama = txtOdeme4Aciklama.Text;
                ayr.Sifre = Licence.Licence.ToMD5("Dbt.2018");
                db.Ayarlar.Add(ayr);
                db.SaveChanges();
                MessageBox.Show("Ayarlar Kaydedilmiştir.");
            }
            else
            {
                var ayr = db.Ayarlar.FirstOrDefault();
                ayr.Nakit_Seri_No = txtNakitSeri.Text;
                ayr.Depo_Kodu = txtDepoKodu.EditValue.ToString();
                ayr.Cari_Kodu = txtCariKodu.EditValue.ToString();
                ayr.Kurulum_Tarihi = Convert.ToDateTime(txtTarih.Text);
                ayr.Plasiyer_Kodu = txtPlasiyerKodu.EditValue.ToString();
                ayr.Kasa_Seri = txtKasaSeri.Text;
                ayr.Nakit_Kasa_Kodu = txtNakitKasa.EditValue.ToString();
                ayr.KKart_Kasa_Kodu = txtKartKasakodu.EditValue.ToString();
                ayr.KKart_Kasa_Aciklama = txtKKartKasaAciklama.Text;
                ayr.Odeme_Sekil1_Kodu = txtOdeme1Kodu.EditValue.ToString();
                ayr.Odeme_Sekil1_Aciklama = txtOdeme1Aciklama.Text;
                ayr.Odeme_Sekil2_Kodu = txtOdeme2Kodu.EditValue.ToString();
                ayr.Odeme_Sekil2_Aciklama = txtOdeme2Aciklama.Text;
                ayr.Odeme_Sekil3_Kodu = txtOdeme3Kodu.EditValue.ToString();
                ayr.Odeme_Sekil3_Aciklama = txtOdeme3Aciklama.Text;
                ayr.Odeme_Sekil4_Kodu = txtOdeme4Kodu.EditValue.ToString();
                ayr.Odeme_Sekil4_Aciklama = txtOdeme4Aciklama.Text;
                ayr.Sifre = Licence.Licence.ToMD5("Dbt.2018");
                db.SaveChanges();
                MessageBox.Show("Ayarlar Güncellenmiştir.");
            }
            AyarlarForm_Load(sender, e);
        }

        private void AyarlarForm_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'caripersoneldataset.CARI_PERSONEL_TANIMLARI' table. You can move, or remove it, as needed.
            this.cARI_PERSONEL_TANIMLARITableAdapter1.Fill(this.caripersoneldataset.CARI_PERSONEL_TANIMLARI);
            // TODO: This line of code loads data into the 'carihesaplarDataset.CARI_HESAPLAR' table. You can move, or remove it, as needed.
            this.cARI_HESAPLARTableAdapter1.Fill(this.carihesaplarDataset.CARI_HESAPLAR);
            // TODO: This line of code loads data into the 'depolardataset.DEPOLAR' table. You can move, or remove it, as needed.
            this.dEPOLARTableAdapter1.Fill(this.depolardataset.DEPOLAR);
            // TODO: This line of code loads data into the 'kasalaeDataSet.KASALAR' table. You can move, or remove it, as needed.
            this.kASALARTableAdapter.Fill(this.kasalaeDataSet.KASALAR);
            // TODO: This line of code loads data into the 'mikroDB_V15_KOZYENIDataSet.CARI_PERSONEL_TANIMLARI' table. You can move, or remove it, as needed.
            this.cARI_PERSONEL_TANIMLARITableAdapter.Fill(this.mikroDB_V15_KOZYENIDataSet.CARI_PERSONEL_TANIMLARI);
            // TODO: This line of code loads data into the 'mikroDB_V15_KOZYENIDataSet.CARI_HESAPLAR' table. You can move, or remove it, as needed.


            txtTarih.Text = DateTime.Now.ToString();
            var sorgu = db.Ayarlar.Select(u => u).FirstOrDefault();
            if (sorgu != null)
            {
                txtNakitSeri.Text = sorgu.Nakit_Seri_No;
                txtDepoKodu.Text= sorgu.Depo_Kodu;
                txtCariKodu.Text = sorgu.Cari_Kodu;
                txtTarih.Text = sorgu.Kurulum_Tarihi.ToString();
                txtPlasiyerKodu.Text = sorgu.Plasiyer_Kodu;
                txtKasaSeri.Text = sorgu.Kasa_Seri;
                txtNakitKasa.Text = sorgu.Nakit_Kasa_Kodu ;
                txtKartKasakodu.Text = sorgu.KKart_Kasa_Kodu;
                txtKKartKasaAciklama.Text = sorgu.KKart_Kasa_Aciklama;
                txtOdeme1Aciklama.Text = sorgu.Odeme_Sekil1_Aciklama;
                txtOdeme1Kodu.Text = sorgu.Odeme_Sekil1_Kodu;
                txtOdeme2Aciklama.Text = sorgu.Odeme_Sekil2_Aciklama;
                txtOdeme2Kodu.Text = sorgu.Odeme_Sekil2_Kodu;
                txtOdeme3Aciklama.Text = sorgu.Odeme_Sekil3_Aciklama;
                txtOdeme3Kodu.Text = sorgu.Odeme_Sekil3_Kodu;
                txtOdeme4Aciklama.Text = sorgu.Odeme_Sekil4_Aciklama;
                txtOdeme4Kodu.Text = sorgu.Odeme_Sekil4_Kodu;

                BtnSil.Enabled = true;
            }
            else
            {
                BtnSil.Enabled = false;
            }

        }

        private void BtnSil_Click(object sender, EventArgs e)
        {
            var id = db.Ayarlar.FirstOrDefault();
            db.Ayarlar.Remove(id);
            db.SaveChanges();
            Temizle();
            AyarlarForm_Load(sender, e);
        }
        private void Temizle()
        {
            txtNakitSeri.Text = "";
            txtDepoKodu.Text ="";
            txtCariKodu.Text = "";
            txtTarih.Text = "";
            txtPlasiyerKodu.Text = "";
            txtKasaSeri.Text = "";
            txtNakitKasa.Text = "";
            txtKartKasakodu.Text = "";
            txtKKartKasaAciklama.Text = "";
            txtOdeme1Aciklama.Text = "";
            txtOdeme1Kodu.Text = "";
            txtOdeme2Aciklama.Text = "";
            txtOdeme2Kodu.Text = "";
            txtOdeme3Aciklama.Text = "";
            txtOdeme3Kodu.Text = "";
            txtOdeme4Aciklama.Text = "";
            txtOdeme4Kodu.Text = "";
        }
   
        private void txtNakitKasa_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void VeritabaniBtn_Click(object sender, EventArgs e)
        {
            DatabaseAyari db = new DatabaseAyari();
            db.ShowDialog();

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            KulllaniciEkle kul = new KulllaniciEkle();
            kul.ShowDialog();
        }

    }
}
